x-common-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

x-restart-policy: &restart-policy
  restart: unless-stopped

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    <<: *restart-policy

    env_file: .env

    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro

    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    logging: *default-logging

    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    <<: *restart-policy

    env_file:
      - .env

    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    logging: *default-logging

    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    <<: *restart-policy

    env_file: .env

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

    logging: *default-logging

    networks:
      - backend

# DEV
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    <<: *restart-policy
    profiles:
      - dev

    ports:
      - "5540:5540"

    volumes:
      - redis_insight_data:/data

    depends_on:
      redis:
        condition: service_healthy

    logging: *default-logging

    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    <<: *restart-policy

    profiles:
      - dev

    env_file: .env

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      postgres:
        condition: service_healthy

    logging: *default-logging

    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  postgres_backups:
  rabbitmq_data:
  redis_data:
  pgadmin_data:
  redis_insight_data: